name: Run Programming Language Tests

on:
  push:
    paths:
      - 'solutions/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'solutions/**'
      - 'tests/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install required compilers and runtimes (optimized for speed)
      - name: Setup C/C++ Compiler
        run: sudo apt-get update && sudo apt-get install -y gcc g++

      - name: Setup Java (Fast)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Detect Changed Files
      - name: Detect Changed Files
        id: changed-files
        run: |
          echo "Detecting modified solution files..."
          git diff --name-only HEAD~1 > changed_files.txt
          cat changed_files.txt

      # Run C Tests if solution.c is modified
      - name: Compile and Run C Tests
        run: |
          if grep -q 'solutions/solution.c' changed_files.txt; then
            echo "Running C Test Cases..."
            if gcc -o c_test solutions/solution.c tests/test.c -lm; then
              ./c_test || echo "C Test Case Failed"
            else
              echo "C Compilation Failed"
            fi
          else
            echo "No changes detected in solution.c"
          fi

      # Run C++ Tests if solution.cpp is modified
      - name: Compile and Run C++ Tests
        run: |
          if grep -q 'solutions/solution.cpp' changed_files.txt; then
            echo "Running C++ Test Cases..."
            if g++ -o cpp_test solutions/solution.cpp tests/test.cpp; then
              ./cpp_test || echo "C++ Test Case Failed"
            else
              echo "C++ Compilation Failed"
            fi
          else
            echo "No changes detected in solution.cpp"
          fi

      # Run Java Tests if Solution.java is modified
      - name: Compile and Run Java Tests
        run: |
          if grep -q 'solutions/Solution.java' changed_files.txt; then
            echo "Running Java Test Cases..."
            if javac -d . solutions/Solution.java tests/Test.java; then
              java tests.Test || echo "Java Test Case Failed"
            else
              echo "Java Compilation Failed"
            fi
          else
            echo "No changes detected in Solution.java"
          fi

      # Run Python Tests if solution.py is modified
      - name: Run Python Tests
        run: |
          if grep -q 'solutions/solution.py' changed_files.txt; then
            echo "Running Python Test Cases..."
            python3 tests/test.py || echo "Python Test Case Failed"
          else
            echo "No changes detected in solution.py"
          fi
