name: Run Code Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Detect Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v44

    - name: Determine File Types
      id: detect-language
      run: |
        echo "Checking which files changed..."
        CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
        RUN_C=0
        RUN_CPP=0
        RUN_PYTHON=0
        RUN_JAVA=0

        for FILE in $CHANGED_FILES; do
          case "$FILE" in
            *.c) RUN_C=1 ;;
            *.cpp) RUN_CPP=1 ;;
            *.py) RUN_PYTHON=1 ;;
            *.java) RUN_JAVA=1 ;;
          esac
        done

        echo "RUN_C=$RUN_C" >> $GITHUB_ENV
        echo "RUN_CPP=$RUN_CPP" >> $GITHUB_ENV
        echo "RUN_PYTHON=$RUN_PYTHON" >> $GITHUB_ENV
        echo "RUN_JAVA=$RUN_JAVA" >> $GITHUB_ENV

    # Setup Java (Fast)
    - name: Setup Java (Fast)
      if: env.RUN_JAVA == '1'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Setup Python (Fast)
    - name: Setup Python (Fast)
      if: env.RUN_PYTHON == '1'
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    # Install C and C++ Dependencies Only If Needed
    - name: Install C/C++ Compilers
      run: |
        sudo apt-get update
        [[ "$RUN_C" == "1" ]] && sudo apt-get install -y gcc
        [[ "$RUN_CPP" == "1" ]] && sudo apt-get install -y g++

    # Compile and Run C Tests
    - name: Compile and Run C Tests
      if: env.RUN_C == '1'
      run: |
        echo "Running C Test Cases..."
        gcc -o tests/test tests/test.c solutions/solution.c
        ./tests/test

    # Compile and Run C++ Tests
    - name: Compile and Run C++ Tests
      if: env.RUN_CPP == '1'
      run: |
        echo "Running C++ Test Cases..."
        g++ -o tests/test tests/test.cpp solutions/solution.cpp
        ./tests/test

    # Run Python Tests (Formatted Output)
    - name: Run Python Tests (Formatted Output)
      if: env.RUN_PYTHON == '1'
      run: |
        echo "Running Python Test Cases..."
        python3 -m pip install --upgrade pip pytest
        export PYTHONUNBUFFERED=1  
        export PYTHONPATH=$PWD  
        python3 tests/test.py | tee test_results.log

    # Compile and Run Java Tests
    - name: Compile and Run Java Tests
      if: env.RUN_JAVA == '1'
      run: |
        echo "Running Java Test Cases..."
        javac -d . solutions/Solution.java tests/Test.java
        java tests.Test

    # Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.log
