name: Run Programming Language Tests

on:
  push:
    paths:
      - 'solutions/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'solutions/**'
      - 'tests/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install required compilers and runtimes (optimized for speed)
      - name: Setup C/C++ Compiler
        run: sudo apt-get update && sudo apt-get install -y gcc g++

      - name: Setup Java (Fast)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Detect Changed Files
      - name: Detect Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: solutions/*

      # Run C Tests if solution.c is changed (Runnable or Base Code)
      - name: Compile and Run C Tests
        if: contains(steps.changed-files.outputs.all_modified_files, 'solutions/solution.c')
        run: |
          echo "Running C Test Cases..."
          if gcc -o c_test solutions/solution.c tests/test.c -lm; then
            ./c_test || echo "C Test Case Failed"
          else
            echo "C Compilation Failed"
          fi

      # Run C++ Tests if solution.cpp is changed (Runnable or Base Code)
      - name: Compile and Run C++ Tests
        if: contains(steps.changed-files.outputs.all_modified_files, 'solutions/solution.cpp')
        run: |
          echo "Running C++ Test Cases..."
          if g++ -o cpp_test solutions/solution.cpp tests/test.cpp; then
            ./cpp_test || echo "C++ Test Case Failed"
          else
            echo "C++ Compilation Failed"
          fi

      # Run Java Tests if Solution.java is changed (Runnable or Base Code)
      - name: Compile and Run Java Tests
        if: contains(steps.changed-files.outputs.all_modified_files, 'solutions/Solution.java')
        run: |
          echo "Running Java Test Cases..."
          if javac -d . solutions/Solution.java tests/Test.java; then
            java tests.Test || echo "Java Test Case Failed"
          else
            echo "Java Compilation Failed"
          fi

      # Run Python Tests if solution.py is changed (Runnable or Base Code)
      - name: Run Python Tests
        if: contains(steps.changed-files.outputs.all_modified_files, 'solutions/solution.py')
        run: |
          echo "Running Python Test Cases..."
          python3 tests/test.py || echo "Python Test Case Failed"
